version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "hashicorp/terraform"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  - package-ecosystem: "asdf"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
