name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  status:
    types:
      - success

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.state == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Dependabot PR
      run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

