name: Terraform Validation

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up asdf and install Terraform
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
        . ~/.asdf/asdf.sh
        asdf plugin-add terraform || true
        asdf install

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

